=== RuiNeto015/functional_programming/files/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda" type="agendaType"/>
    <xs:complexType name="teacherRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="teacherIDREF" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="teacherType">
        <xs:sequence>
            <xs:element type="availabilityType" name="availability" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="teacherID" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="teacherOrExternalRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="teacherOrExternalIDREF" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="externalType">
        <xs:sequence>
            <xs:element type="availabilityType" name="availability" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="externalID" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="vivaType">
        <xs:sequence>
            <xs:element type="teacherRefType" name="president"/>
            <xs:element type="teacherRefType" name="advisor" maxOccurs="unbounded"/>
            <xs:element type="teacherOrExternalRefType" name="coadvisor" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="teacherOrExternalRefType" name="supervisor" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="student" use="required"/>
        <xs:attribute type="xs:string" name="title" use="required"/>
    </xs:complexType>
    <xs:complexType name="vivasType">
        <xs:sequence>
            <xs:element type="vivaType" name="viva" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="availabilityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:dateTime" name="start" use="required"/>
                <xs:attribute type="xs:dateTime" name="end" use="required"/>
                <xs:attribute type="preferenceType" name="preference" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="teachersType">
        <xs:sequence>
            <xs:element type="teacherType" name="teacher" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="externalsType">
        <xs:sequence>
            <xs:element type="externalType" name="external" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="resourcesType">
        <xs:sequence>
            <xs:element type="teachersType" name="teachers"/>
            <xs:element type="externalsType" name="externals"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="agendaType">
        <xs:sequence>
            <xs:element type="vivasType" name="vivas"/>
            <xs:element type="resourcesType" name="resources"/>
        </xs:sequence>
        <xs:attribute type="xs:time" name="duration" use="required"/>
    </xs:complexType>

    <xs:simpleType name="teacherID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="T[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="teacherIDREF">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="T[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="externalID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="E[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="teacherOrExternalIDREF">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="[TE][0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="preferenceType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== RuiNeto015/functional_programming/files/test/ms03/valid_sample01_in.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../agenda.xsd"
        duration="01:00:00">
    <vivas>
        <viva student="Student 001" title="Title 1">
            <president id="T001"/>
            <advisor id="T002"/>
        </viva>
        <viva student="Student 002" title="Title 2">
            <president id="T002"/>
            <advisor id="T003"/>
        </viva>
        <viva student="Student 003" title="Title 3">
            <president id="T004"/>
            <advisor id="T001"/>
        </viva>
        <viva student="Student 004" title="Title 4">
            <president id="T005"/>
            <advisor id="T006"/>
        </viva>
    </vivas>
    <resources>
        <teachers>
            <teacher id="T001" name="Teacher 001">
                <availability start="2020-05-30T09:00:00" end="2020-05-30T10:00:00" preference="5"/>
                <availability start="2020-05-30T11:00:00" end="2020-05-30T12:00:00" preference="5"/>
            </teacher>

            <teacher id="T002" name="Teacher 002">
                <availability start="2020-05-30T09:00:00" end="2020-05-30T11:00:00" preference="5"/>
            </teacher>

            <teacher id="T003" name="Teacher 003">
                <availability start="2020-05-30T09:50:00" end="2020-05-30T12:00:00" preference="5"/>
            </teacher>

            <teacher id="T004" name="Teacher 004">
                <availability start="2020-05-30T09:00:00" end="2020-05-30T10:00:00" preference="5"/>
                <availability start="2020-05-30T11:00:00" end="2020-05-30T12:00:00" preference="5"/>
            </teacher>

            <teacher id="T005" name="Teacher 005">
                <availability start="2020-05-30T09:00:00" end="2020-05-30T10:00:00" preference="1"/>
                <availability start="2020-05-30T11:00:00" end="2020-05-30T12:00:00" preference="3"/>
                <availability start="2020-05-30T12:00:00" end="2020-05-30T13:00:00" preference="5"/>
            </teacher>

            <teacher id="T006" name="Teacher 006">
                <availability start="2020-05-30T09:00:00" end="2020-05-30T10:00:00" preference="1"/>
                <availability start="2020-05-30T11:00:00" end="2020-05-30T13:00:00" preference="4"/>
            </teacher>
        </teachers>
        <externals>
        </externals>
    </resources>
</agenda>

=== RuiNeto015/functional_programming/files/test/ms01/valid_sample02_in.xml
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../agenda.xsd"
        duration="01:00:00">
    <vivas>
        <viva student="Student 001" title="Title 1">
            <president id="T001"/>
            <advisor id="T002"/>
            <supervisor id="E001"/>
        </viva>
        <viva student="Student 002" title="Title 2">
            <president id="T002"/>
            <advisor id="T003"/>
            <coadvisor id="E002"/>
        </viva>
    </vivas>
    <resources>
        <teachers>
            <teacher id="T001" name="Teacher 001">
                <availability start="2024-05-30T09:30:00" end="2024-05-30T12:30:00" preference="5"/>
                <availability start="2024-05-30T13:30:00" end="2024-05-30T16:30:00" preference="3"/>
            </teacher>
            <teacher id="T002" name="Teacher 002">
                <availability start="2024-05-30T10:30:00" end="2024-05-30T11:30:00" preference="5"/>
                <availability start="2024-05-30T14:30:00" end="2024-05-30T17:00:00" preference="5"/>
            </teacher>
            <teacher id="T003" name="Teacher 003">
                <availability start="2024-05-30T08:00:00" end="2024-05-30T12:00:00" preference="4"/>
                <availability start="2024-05-30T14:00:00" end="2024-05-30T15:00:00" preference="5"/>
            </teacher>
        </teachers>
        <externals>
            <external id="E001" name="External 001">
                <availability start="2024-05-30T08:00:00" end="2024-05-30T10:00:00" preference="2"/>
                <availability start="2024-05-30T15:00:00" end="2024-05-30T16:30:00" preference="5"/>
            </external>
            <external id="E002" name="External 002">
                <availability start="2024-05-30T09:30:00" end="2024-05-30T11:45:00" preference="3"/>
            </external>
        </externals>
    </resources>
</agenda>

=== RuiNeto015/functional_programming/files/assessment/ms03/valid_agenda_01_in.xml
<?xml version='1.0' encoding="UTF-8"?>
<agenda
        xsi:noNamespaceSchemaLocation="../../agenda.xsd" duration="01:00:00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <vivas>
        <viva student="Student001" title="Student001">
            <president id="T002"/>
            <advisor id="T001"/>
            <coadvisor id="E001"/>
            <coadvisor id="E002"/>
        </viva>
        <viva student="Student002" title="Student002">
            <president id="T002"/>
            <advisor id="T001"/>
            <supervisor id="E002"/>
        </viva>
        <viva student="Student003" title="Student003">
            <president id="T001"/>
            <advisor id="T002"/>
            <supervisor id="E002"/>
        </viva>
        <viva student="Student004" title="Student004">
            <president id="T001"/>
            <advisor id="T002"/>
            <coadvisor id="E001"/>
            <coadvisor id="E002"/>
        </viva>
        <viva student="Student005" title="Student005">
            <president id="T001"/>
            <advisor id="T002"/>
        </viva>
        <viva student="Student006" title="Student006">
            <president id="T001"/>
            <advisor id="T002"/>
            <coadvisor id="E001"/>
        </viva>
        <viva student="Student007" title="Student007">
            <president id="T002"/>
            <advisor id="T001"/>
            <supervisor id="E001"/>
            <supervisor id="E002"/>
        </viva>
        <viva student="Student008" title="Student008">
            <president id="T001"/>
            <advisor id="T002"/>
            <coadvisor id="E002"/>
        </viva>
        <viva student="Student009" title="Student009">
            <president id="T002"/>
            <advisor id="T001"/>
        </viva>
    </vivas>
    <resources>
        <teachers>
            <teacher id="T002" name="T002">
                <availability start="2024-06-10T10:30:00" end="2024-06-10T11:30:00" preference="1"/>
                <availability start="2024-06-24T17:45:00" end="2024-06-24T18:45:00" preference="1"/>
                <availability start="2024-06-05T09:00:00" end="2024-06-05T11:15:00" preference="4"/>
                <availability start="2024-06-13T08:30:00" end="2024-06-13T09:30:00" preference="3"/>
                <availability start="2024-06-21T14:00:00" end="2024-06-21T15:00:00" preference="1"/>
                <availability start="2024-06-20T08:34:00" end="2024-06-20T10:30:00" preference="5"/>
                <availability start="2024-06-20T14:44:00" end="2024-06-20T15:45:00" preference="5"/>
                <availability start="2024-06-08T15:15:00" end="2024-06-08T19:01:00" preference="4"/>
                <availability start="2024-06-04T13:00:00" end="2024-06-04T18:15:00" preference="1"/>
                <availability start="2024-06-19T11:04:00" end="2024-06-19T13:00:00" preference="5"/>
                <availability start="2024-06-23T09:20:00" end="2024-06-23T11:15:00" preference="1"/>
                <availability start="2024-06-18T13:45:00" end="2024-06-18T18:45:00" preference="5"/>
            </teacher>
            <teacher id="T001" name="T001">
                <availability start="2024-06-08T16:00:00" end="2024-06-08T17:00:00" preference="5"/>
                <availability start="2024-06-07T10:00:00" end="2024-06-07T11:00:00" preference="1"/>
                <availability start="2024-06-26T18:00:00" end="2024-06-26T19:00:00" preference="1"/>
                <availability start="2024-06-17T17:00:00" end="2024-06-17T18:00:00" preference="1"/>
                <availability start="2024-06-30T09:45:00" end="2024-06-30T10:45:00" preference="5"/>
                <availability start="2024-06-29T15:15:00" end="2024-06-29T16:15:00" preference="3"/>
                <availability start="2024-06-10T08:45:00" end="2024-06-10T09:45:00" preference="1"/>
                <availability start="2024-06-20T13:30:00" end="2024-06-20T14:30:00" preference="5"/>
                <availability start="2024-06-02T16:00:00" end="2024-06-02T17:00:00" preference="5"/>
                <availability start="2024-06-23T15:45:00" end="2024-06-23T16:45:00" preference="3"/>
                <availability start="2024-06-03T15:15:00" end="2024-06-03T16:15:00" preference="2"/>
                <availability start="2024-06-20T07:37:00" end="2024-06-20T12:30:00" preference="5"/>
                <availability start="2024-06-20T14:44:00" end="2024-06-20T17:12:00" preference="5"/>
                <availability start="2024-06-08T17:14:00" end="2024-06-08T18:16:00" preference="4"/>
                <availability start="2024-06-04T14:47:00" end="2024-06-04T17:51:00" preference="1"/>
                <availability start="2024-06-19T11:59:00" end="2024-06-19T15:00:00" preference="5"/>
                <availability start="2024-06-23T10:01:00" end="2024-06-23T12:03:00" preference="1"/>
                <availability start="2024-06-18T15:45:00" end="2024-06-18T17:43:00" preference="5"/>
                <availability start="2024-06-05T08:35:00" end="2024-06-05T11:15:00" preference="4"/>
            </teacher>
        </teachers>
        <externals>
            <external id="E001" name="E001">
                <availability start="2024-06-26T15:15:00" end="2024-06-26T16:30:00" preference="5"/>
                <availability start="2024-06-27T08:15:00" end="2024-06-27T09:15:00" preference="1"/>
                <availability start="2024-06-29T13:00:00" end="2024-06-29T14:00:00" preference="5"/>
                <availability start="2024-06-15T09:00:00" end="2024-06-15T10:00:00" preference="5"/>
                <availability start="2024-06-08T17:05:00" end="2024-06-08T20:12:00" preference="4"/>
                <availability start="2024-06-04T14:19:00" end="2024-06-04T18:15:00" preference="1"/>
                <availability start="2024-06-05T08:48:00" end="2024-06-05T11:16:00" preference="4"/>
            </external>
            <external id="E002" name="E002">
                <availability start="2024-06-20T12:45:00" end="2024-06-20T17:42:00" preference="5"/>
                <availability start="2024-06-17T10:15:00" end="2024-06-17T11:15:00" preference="5"/>
                <availability start="2024-06-02T15:45:00" end="2024-06-02T16:45:00" preference="3"/>
                <availability start="2024-06-16T17:00:00" end="2024-06-16T18:00:00" preference="1"/>
                <availability start="2024-06-30T14:45:00" end="2024-06-30T15:45:00" preference="1"/>
                <availability start="2024-06-08T16:22:00" end="2024-06-08T18:15:00" preference="4"/>
                <availability start="2024-06-04T13:00:00" end="2024-06-04T16:18:00" preference="1"/>
                <availability start="2024-06-23T09:47:00" end="2024-06-23T13:15:00" preference="1"/>
                <availability start="2024-06-18T13:45:00" end="2024-06-18T18:45:00" preference="5"/>
                <availability start="2024-06-05T08:48:00" end="2024-06-05T12:16:00" preference="4"/>
            </external>
        </externals>
    </resources>
</agenda>
